# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gbox < Formula
  desc "Gbox - use github as storage"
  homepage "https://github.com/zezaeoh/gbox"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zezaeoh/gbox/releases/download/v0.1.1/gbox_0.1.1_Darwin_arm64.tar.gz"
      sha256 "0a8deeed7ce7ae353610873a675e0fbefffcfd80285f4c023891df75a2b29451"

      def install
        bin.install "gbox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zezaeoh/gbox/releases/download/v0.1.1/gbox_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "c03ab800ff78e2352f8c78768d498852d02960c1f2768c7198e8f0460af07693"

      def install
        bin.install "gbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zezaeoh/gbox/releases/download/v0.1.1/gbox_0.1.1_Linux_x86_64.tar.gz"
      sha256 "1fde50d8a997f858949ad9a2891d61fbf28fe9a9eef28f56a777d0396b492105"

      def install
        bin.install "gbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zezaeoh/gbox/releases/download/v0.1.1/gbox_0.1.1_Linux_arm64.tar.gz"
      sha256 "204fdddf8a4b98794fca4c2e5539eaa33c89566fa619684019a12810067e5154"

      def install
        bin.install "gbox"
      end
    end
  end

  test do
    system "gbox version"
  end
end
