# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gbox < Formula
  desc "Gbox - use github as storage"
  homepage "https://github.com/zezaeoh/gbox"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zezaeoh/gbox/releases/download/v0.1.2/gbox_Darwin_arm64.tar.gz"
      sha256 "89f368d46670261cf005f5cdb3fff9f38f71753afb060aa6f49623d071e49362"

      def install
        bin.install "gbox"

        # Install bash completion
        output = Utils.popen_read("#{bin}/gbox completion bash")
        (bash_completion/"gbox").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/gbox completion zsh")
        (zsh_completion/"_gbox").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zezaeoh/gbox/releases/download/v0.1.2/gbox_Darwin_amd64.tar.gz"
      sha256 "484d6c157b640790406f70efececcb46c5a6c87a54fb03679e4247bb2309a444"

      def install
        bin.install "gbox"

        # Install bash completion
        output = Utils.popen_read("#{bin}/gbox completion bash")
        (bash_completion/"gbox").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/gbox completion zsh")
        (zsh_completion/"_gbox").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zezaeoh/gbox/releases/download/v0.1.2/gbox_Linux_armv6.tar.gz"
      sha256 "2775d8aa432c9882945c5bf5c428e97c8ccdbad532d799b3cc7861a0b29c06f9"

      def install
        bin.install "gbox"

        # Install bash completion
        output = Utils.popen_read("#{bin}/gbox completion bash")
        (bash_completion/"gbox").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/gbox completion zsh")
        (zsh_completion/"_gbox").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zezaeoh/gbox/releases/download/v0.1.2/gbox_Linux_arm64.tar.gz"
      sha256 "3227cb6499613bc381b28fe68d22b792351f1b80e90164e17cc47eebb2487605"

      def install
        bin.install "gbox"

        # Install bash completion
        output = Utils.popen_read("#{bin}/gbox completion bash")
        (bash_completion/"gbox").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/gbox completion zsh")
        (zsh_completion/"_gbox").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zezaeoh/gbox/releases/download/v0.1.2/gbox_Linux_amd64.tar.gz"
      sha256 "8c6186083b41cef21907f60c5789cf8d9b50029c0ff3c73d9545efd41e4e6f85"

      def install
        bin.install "gbox"

        # Install bash completion
        output = Utils.popen_read("#{bin}/gbox completion bash")
        (bash_completion/"gbox").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/gbox completion zsh")
        (zsh_completion/"_gbox").write output
      end
    end
  end

  test do
    system "gbox version"
  end
end
